driver_info = {
    "HAM": {"name": "Lewis Hamilton", "number": "44"},
    "VER": {"name": "Max Verstappen", "number": "1"},
    "LEC": {"name": "Charles Leclerc", "number": "16"},
    "NOR": {"name": "Lando Norris", "number": "4"},
    "SAI": {"name": "Carlos Sainz", "number": "55"},
    "ALO": {"name": "Fernando Alonso", "number": "14"},
    "RUS": {"name": "George Russell", "number": "63"},
    "PER": {"name": "Sergio Perez", "number": "11"},
    "PIA": {"name": "Oscar Piastri", "number": "81"},
    "TSU": {"name": "Yuki Tsunoda", "number": "22"},
    "ALB": {"name": "Alex Albon", "number": "23"},
    "MAG": {"name": "Kevin Magnussen", "number": "20"},
    "HUL": {"name": "Nico Hülkenberg", "number": "27"},
    "GAS": {"name": "Pierre Gasly", "number": "10"},
    "OCO": {"name": "Esteban Ocon", "number": "31"},
    "BOT": {"name": "Valtteri Bottas", "number": "77"},
    "ZHO": {"name": "Zhou Guanyu", "number": "24"},
    "RIC": {"name": "Daniel Ricciardo", "number": "3"},
    "LAW": {"name": "Liam Lawson", "number": "40"},
    "SAR": {"name": "Logan Sargeant", "number": "2"},
}
